"""Migrations

Revision ID: 3c3eedb25269
Revises: 
Create Date: 2024-07-10 14:14:51.594924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c3eedb25269'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'bio')
    op.drop_column('clients', 'bio_data')
    op.add_column('users', sa.Column('bio', sa.String(length=60), nullable=True))
    op.drop_column('workers', 'bio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('bio', sa.VARCHAR(length=60), nullable=True))
    op.drop_column('users', 'bio')
    op.add_column('clients', sa.Column('bio_data', sa.VARCHAR(length=60), nullable=True))
    op.add_column('admins', sa.Column('bio', sa.VARCHAR(length=60), nullable=True))
    # ### end Alembic commands ###
